### PR TITLE
update Dockerfile with new jupyter/scipy-notebook and packages

### PR DESCRIPTION
**Pull request by xgirouxb**
Updates for Dockerfile, including newest versions of jupyter scipy notebook Docker and other packages used in the jupyter scipy ee notebook

### CODE REVIEW

**Review by tylere — COMMENTED** [review]
When I try to build the docker image, I get the error:

> CommandNotFoundError: To use 'conda build', install conda-build.

Can you confirm that it builds for you?

**Comment by xgirouxb** [comment]
That seems to have been a mistake on my part, I followed some suggestions in the error messages during the build and added them to the Dockerfile without testing. Essentially, the command `conda clean -tipsy` should be replaced by `conda clean --all -f -y`. I can go ahead and commit the proper changes. However, before I do so I have encountered 2 futher problems while using this build for the last 2 weeks:

1. The base notebook on which all the Jupyter dockers are built currently installs `jupyterlab 1.0.4` (see line 107 in [this](https://github.com/jupyter/docker-stacks/blob/d5d50848a633bf1875d9de4e8b1c339181b2073f/base-notebook/Dockerfile) Dockerfile). As it currently stands, after I build the jupyterlab notebook for earth engine, the UI has significant glitches, a bug that is mentioned on the [jupyterlab repo](https://github.com/jupyterlab/jupyterlab/issues/7178). As a workaround for now, I simply run `conda install jupyterlab=1.1.2` after the image is built and the container is deployed, and that seems to fix the issue entirely.
2. When using the earthengine CLI, there are a few error messages that appear to be related to a compatibility issue between `tensorflow 1.13.1` and `numpy 1.17.2` (see [this issue](https://github.com/tensorflow/tensorflow/issues/30427) on the tensorflow repo). A workaround that fixes things for now is to run `conda install numpy=1.16.4`, which again I run once everything is built and up and running.

I am assuming both these issues will be fixed when tensorflow releases version 1.14.1 and when jupyter updates all their Dockerfiles so they build images with jupyterlab 1.1.2. However, I was wondering what changes to the Dockerfile you would recommend for our current purposes. For now I have fixed these issues after building the docker image because they are quite bothersome, but I can certainly add them in to the Dockerfile on a temporary basis, and eventualy update it when these issues are fixed upstream. I noticed you added version arguments for all the packages in the intro of the Dockerfile, do you think that adding those two lines directly in the conda install call without adding version arguments would be an acceptable workaround for now? I have tested it and it works.

**Comment by tylere** [comment]
Version compatibility is often a challenge. I would suggest including your version adjustments for jupyterlab and numpy in the Dockerfile, along with comments that indicate why the versions are being adjusted so that they can be removed later when the base image is updated.

**Comment by xgirouxb** [comment]
I completed all the changes in the last commit and tested it, everything seems good to go.

**Pull request merged**
