### PR TITLE
Atmospheric Correction Dockerfile

### PR DESCRIPTION
**Pull request by samsammurphy**
Atmospheric correction using Py6S with Earth Engine. Setup for use with a Jupyter Notebook. Sentinel 2 example provided.

### CODE REVIEW

**Comment by samsammurphy** [comment]
I was also thinking including a before and after (to show users what to expect) but wasn't sure about commiting image files to the repo's history.

### before
sentinel2_before

### after
sentinel2_after

**Comment by tylere** [comment]
If the images are for documentation, I would probably not add them to the repo. Instead, try this: https://stackoverflow.com/a/20959426/2196694

If the images are used for testing the code, then yes I would add them to the repo.

**Comment by samsammurphy** [comment]
Thanks Tyler! That seems to work. Images below use URLs from the closed issue.



after

**Comment by gena** [comment]
Looks a bit like a hack :), more appropriate might be to use lfs: https://git-lfs.github.com/

**Comment by samsammurphy** [comment]
For sure @gena 😄     

This is the reponse I got from git-lfs

```
$ git push origin
batch response: @samsammurphy can not upload new objects to public fork samsammurphy/ee-jupyter-contrib
```
I think you can't push LFS assets to a public fork unless the original repo already has LFS objects, or you have push access to the original repo [[1]](https://github.com/git-lfs/git-lfs/issues/1449). I might need github enterprise [[2]](https://github.com/git-lfs/git-lfs/issues/1906)?

Just for fun I tried hosting on Google Drive but.. image not shown

There might be a way to make Googe Drive provide simple URLs that markdown understands, like AWS:

**Comment by gena** [comment]
Yeah, lfs was not enabled, I've enabled it, not sure it will work with forks now. Otherwise, making branch in this repository should be fine.

**Pull request merged**
